#!/bin/sh
# shellcheck disable=SC2155

# Profil-Datei, wird beim Login ausgeführt. Umgebungsvariablen werden hier gesetzt.

# Füge alle Verzeichnisse in `~/.local/bin` zum $PATH hinzu
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Deaktiviere die PROMPT_SP-Option, falls sie gesetzt ist
unsetopt PROMPT_SP 2>/dev/null

# Standardprogramme:
export EDITOR="nvim"
export TERMINAL="st"
export TERMINAL_PROG="st"
export BROWSER="librewolf"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

# Ändere die Standardseiten für Krypto-/Wetterüberwachung.
export CRYPTOURL="rate.sx"
export WTTRURL="wttr.in"

	# Aufräumen im Home-Verzeichnis:
export XDG_CONFIG_HOME="$HOME/.config"				# Konfigurationsdateien
export XDG_DATA_HOME="$HOME/.local/share"			# Anwendungsdaten
export XDG_CACHE_HOME="$HOME/.cache"				# Zwischengespeicherte Daten
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"			# X-Server-Startdatei
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"		# Diese Zeile kann einige Desktop-Manager stören.
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"		# Notmuch E-Mail-Konfigurationsdatei
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"	# GTK2-Konfigurationsdatei
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"			# Wget-Konfigurationsdatei
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"			# Input-Konfigurationsdatei
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"				# Zsh-Konfigurationsverzeichnis
#export GNUPGHOME="$XDG_DATA_HOME/gnupg"			# GnuPG Home-Verzeichnis
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"		# Wine Präfix-Verzeichnis
export KODI_DATA="$XDG_DATA_HOME/kodi"				# Kodi Datenverzeichnis
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"	# Passwortspeicher
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"				# Tmux temporäres Verzeichnis
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"		# Android SDK Verzeichnis
export CARGO_HOME="$XDG_DATA_HOME/cargo"			# Rust Cargo Verzeichnis
export GOPATH="$XDG_DATA_HOME/go"				# Go Arbeitsverzeichnis
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"			# Go Modul-Cache
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"	# Ansible Konfigurationsdatei
export UNISON="$XDG_DATA_HOME/unison"				# Unison Verzeichnis
export HISTFILE="$XDG_DATA_HOME/history"			# Historien-Datei
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"		# Mbsync Konfigurationsdatei
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"			# Electrum Verzeichnis
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"		# Python Startdatei
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"		# SQLite Historie

	# Andere Programmeinstellungen:
export DICS="/usr/share/stardict/dic/"				# Verzeichnis für Stardict-Wörterbücher
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"		# Sudo Passwortabfrageprogramm
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"		# FZF Standardoptionen
export LESS="R"							# Less Pager Optionen
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"		# Less Farbanpassungen
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"	# Syntax-Hervorhebung für Less
export QT_QPA_PLATFORMTHEME="gtk2"				# QT soll gtk2-Thema verwenden
export QT_AUTO_SCREEN_SCALE_FACTOR=1			# testeinstellungen von Arch-Wiki
export QT_ENABLE_HIGHDPI_SCALING=1			# testeinstellungen aus der Arch-Wiki
# export QT_QPA_PLATFORMTHEME="gtk3"				# QT soll gtk3-Thema verwenden
# export QT_QPA_PLATFORMTHEME="qt5ct"				# qt5ct benötigt
# export QT_SCALE_FACTOR=1.5  					# Für Qt-Anwendungen
# export GDK_SCALE=2          					# Für GTK-Anwendungen
# export GDK_DPI_SCALE=0.5    					# Korrigiert die Schriftgrößen bei GDK_SCALE=2
export MOZ_USE_XINPUT2=1					# Mozilla Smooth Scrolling für Touchpads
export AWT_TOOLKIT="MToolkit wmname LG3D"			# Fix für Java-Anwendungen in dwm
export _JAVA_AWT_WM_NONREPARENTING=1				# Weiterer Fix für Java-Anwendungen in dwm

	# Prüfe, ob die Shortcut-Konfigurationsdatei existiert und starte das Shortcuts-Programm falls nicht
[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1

	# Starte den grafischen Server auf dem aktuellen tty des Benutzers, falls nicht bereits laufend
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

	# Tausche Escape und Caps Lock, wenn tty und kein Passwort benötigt:
sudo -n loadkeys "$XDG_DATA_HOME/larbs/ttymaps.kmap" 2>/dev/null
