#!/bin/sh

# Diese Datei wird ausgeführt, wenn ein Display Manager Sie in eine grafische
# Sitzung einloggt. Wenn Sie startx/xinit wie ein Profi verwenden, wird diese
# Datei ebenfalls geladen.

# === DPI Einstellungen ===
xrandr --dpi 96

# === Themes und GUI ===
# export QT_QPA_PLATFORMTHEME="gtk2"
# export GTK_SCALE=1.4
# export QT_QPA_PLATFORMTHEME=qt5ct
# export GDK_SCALE=2
# export GDK_DPI_SCALE=0.5

# Don't Randomly Turn off
# TODO Testen...
# xset s off
# xset -dpms
# xset s noblank

# Hide mouse when typing
# xbanish &

# Setzt den Hintergrund mit dem `setbg` Skript
setbg &

# Lädt Xresources Farben/Einstellungen beim Start
# TODO Trennen von Skalierung und Farben
# wenn xrdb aktiviert, dann "~/.config/x11/xresources" beachten
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

# === Liste der automatisch zu startenden Programme ===
autostart="mpd xcompmgr dunst unclutter pipewire remapd"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Aktiviert Natural Scrolling (Mac-like)
# xinput set-prop 10 "libinput Natural Scrolling Enabled" 1

# Stellt sicher, dass xrdb fertig ist, bevor der Window Manager / Desktop Environment gestartet wird
[ -n "$xrdbpid" ] && wait "$xrdbpid"
